### ISSUE TITLE
Bus.close() crashes with ConcurrentModificationException

### ISSUE THREAD

**Issue by gmk57** [vltgroup/ccTalk#3]
We're trying to implement ccTalk on Android, and your library is of great help. Thanks!

Currently we struggle with handling disconnection/reconnection of USB adapter and individual devices.

If we call `Bus.close()`, it crashes with the following stack trace:
```
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
    at java.util.HashMap$EntryIterator.next(HashMap.java:824)
    at java.util.HashMap$EntryIterator.next(HashMap.java:824)
    at com.vltgroup.ccTalk.bus.Bus.close(Bus.java:216)
```

BTW, is there any way to prevent ditching non-responding devices forever after 20 secs? Or to recover from `onDeviceDead`?  Or to search for device(s) without recreating the whole `Bus`?

**Comment by vltgroup** [comment]
Fixed in v3.0
